### ISSUE TITLE
view bot

### ISSUE THREAD

**Issue by Harmanjit14** [Mahiramodi/Mahiramodi#1]
laga le yeh bhi 
`

> <p align="center"> <img src="https://komarev.com/ghpvc/?username=Harmanjit14" alt="Harmanjit14" /> </p>

`

- [ ] `<p align="center"> <img src="https://komarev.com/ghpvc/?username=Harmanjit14" alt="Harmanjit14" /> </p>`

**Comment by Mahiramodi** [comment]
Yr abhi koi views hi nahi hai toh kya hi krna laga ke

**Comment by Mahiramodi** [comment]
Done.
 Thanks👍👍
